kind: Service
apiVersion: v1
metadata:
  name: python-vote-frontend-service
  namespace: XX_NAMESPACE_XX
spec:
  selector:
    app: python-vote-frontend-service
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
